Feature/add new voyages data condensed endpoints
SignalOceanSdk/SignalSDK pull request #177
Opened 2022-05-27 08:48 UTC by edervisis

Added new fields to `VoyagesData` and new dataclass for `VoyagesCondensed`.

2022-05-27 11:14 UTC, gmema requested changes
- In `mkdocs.yml` add the new release note file you created (`Version 1.1.7.md`)

Regarding the change in port congestion, did you face any errors with the previous version? I saw that in the documentation they use the import without `dataset`
https://pypi.org/project/strictly-typed-pandas/

@LamprosArgy has implemented this module, so maybe he can review it too.

2022-05-27 13:53 UTC, edervisis commented
> * In `mkdocs.yml` add the new release note file you created (`Version 1.1.7.md`)
> 
> Regarding the change in port congestion, did you face any errors with the previous version? I saw that in the documentation they use the import without `dataset` https://pypi.org/project/strictly-typed-pandas/
> 
> @LamprosArgy has implemented this module, so maybe he can review it too.

Updated the mkdocs,yml

Regarding the import edit, we had problems with the import when running the build.sh script, which failed with an error and could not continue with the rest of the checks. The error in question was:
```
Running type checks...
signal_ocean/port_congestion/port_congestion.py:5: error: Module 'strictly_typed_pandas' has no attribute 'DataSet'
```
Updating the import to `from strictly_typed_pandas.dataset import DataSet` fixed that. Please check if you can confirm the error.

2022-05-30 10:11 UTC, gmema commented
@edervisis Regarding the error with strictly_typed_pandas you are right about it. 
Please check why the PR is failing, make a re-request and then I can approve it.

2022-05-30 14:11 UTC, gmema approved these changes

2022-05-31 09:28 UTC, merged