Add vessels and companies APIs
SignalOceanSdk/SignalSDK pull request #2
Opened 2020-10-01 15:17 UTC by abelesiotis-signal

2020-10-08 10:05 UTC, pogrodowczyk commented
Until we automate it with a Git hook, please clear all outputs in the notebooks before committing. Otherwise, `.ipynb` files become large and can produce unnecessary diffs when new commits are made.

2020-10-08 10:58 UTC, pogrodowczyk commented
The build fails when running type checks:
```
Running type checks...
signal_ocean/util/parsing_helpers.py:21: error: Missing type parameters for generic type "Type"
signal_ocean/util/parsing_helpers.py:48: error: Argument 1 to "int" has incompatible type "Union[str, int, float, bool, None]"; expected "Union[str, bytes, SupportsInt, _SupportsIndex]"
signal_ocean/util/parsing_helpers.py:50: error: Argument 1 to "float" has incompatible type "Union[str, int, float, bool, None]"; expected "Union[SupportsFloat, _SupportsIndex, str, bytes, bytearray]"
signal_ocean/util/parsing_helpers.py:54: error: Value of type "Union[str, int, float, bool, None]" is not indexable
signal_ocean/util/parsing_helpers.py:59: error: Missing type parameters for generic type "Type"
signal_ocean/util/parsing_helpers.py:60: error: Implicit generic "Any". Use "typing.List" and specify generic parameters
signal_ocean/util/parsing_helpers.py:92: error: Argument 2 to "isinstance" has incompatible type "object"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
signal_ocean/util/parsing_helpers.py:93: error: Argument 1 to "list" has incompatible type "Union[str, int, float, bool, None]"; expected "Iterable[Any]"
signal_ocean/util/parsing_helpers.py:94: error: Item "int" of "Union[str, int, float, bool, None]" has no attribute "__iter__" (not iterable)
signal_ocean/util/parsing_helpers.py:94: error: Item "float" of "Union[str, int, float, bool, None]" has no attribute "__iter__" (not iterable)
signal_ocean/util/parsing_helpers.py:94: error: Item "bool" of "Union[str, int, float, bool, None]" has no attribute "__iter__" (not iterable)
signal_ocean/util/parsing_helpers.py:94: error: Item "None" of "Union[str, int, float, bool, None]" has no attribute "__iter__" (not iterable)
signal_ocean/util/parsing_helpers.py:100: error: Missing type parameters for generic type "Dict"
signal_ocean/util/parsing_helpers.py:143: error: Too many arguments for "object"
signal_ocean/util/request_helpers.py:38: error: Incompatible return value type (got "None", expected "TModel")
Found 15 errors in 2 files (checked 49 source files)
```

2020-10-15 10:42 UTC, pogrodowczyk requested changes

2020-10-15 10:42 UTC, pogrodowczyk commented on tests/util/test_parsing_helpers.py
> +    if type(expected) == type and issubclass(expected, Exception):
[Conditional test logic](http://xunitpatterns.com/Conditional%20Test%20Logic.html) is a test smell. There should be two tests here: one that asserts that an appropriate exception occurred, and one that asserts that the class was properly parsed.

The same applies to `test_parse_field`.

2020-10-15 10:42 UTC, pogrodowczyk commented on tests/util/test_parsing_helpers.py
> +                               created_date=datetime(2010, 1, 1, 1, 0, 0))
I think that the expectation for the `datetime` should be that it is in UTC, i.e. that it has the `tzinfo=timezone.utc` parameter.

2020-10-15 12:18 UTC, abelesiotis-signal commented on signal_ocean/companies/companies_api.py
> +                name: String to filter and return only companies the name
Yes, will fix.

2020-10-15 12:19 UTC, abelesiotis-signal commented on signal_ocean/companies/models.py
> +    synonyms: Optional[List[str]] = None
Correct, I will change to Tuples and extend the parser.

2020-10-15 12:23 UTC, abelesiotis-signal commented on signal_ocean/util/parsing_helpers.py
> +        return datetime.fromisoformat(value[:19])
OK, I will use the `parse_datetime` for uniformity. Maybe better to change its implementation so that it does not silence errors.

2020-10-15 12:23 UTC, abelesiotis-signal commented on signal_ocean/util/parsing_helpers.py
> +def _parse_class(value: Any, cls: Type[Any]) \
Agree, will fil.

2020-10-15 12:24 UTC, abelesiotis-signal commented on tests/util/test_parsing_helpers.py
> +    if type(expected) == type and issubclass(expected, Exception):
I will split each function to two tests.

2020-10-15 12:25 UTC, abelesiotis-signal commented on tests/util/test_parsing_helpers.py
> +                               created_date=datetime(2010, 1, 1, 1, 0, 0))
Will change it to set tzinfo as utc.

2020-10-15 12:42 UTC, abelesiotis-signal commented on docs/examples/jupyter/CompaniesAPI/CompaniesAPI.ipynb
> +{
The exposed endpoint for companies api was upgraded to v1.1. Will change the code to call the updated one.

2020-10-21 06:48 UTC, pogrodowczyk approved these changes

2020-10-21 09:56 UTC, merged