Pool-1105 port expenses api
SignalOceanSdk/SignalSDK pull request #22
Opened 2020-11-27 13:07 UTC by ktsitsikas-signal

Bare minimum port and canal expenses API implementation

2020-12-10 08:30 UTC, prompanos-signal requested changes

2020-12-10 08:30 UTC, prompanos-signal commented on docs/examples/jupyter/PortExpensesAPI/PortExpensesAPI.ipynb
> +    "api = PortExpensesAPI()"
It is more easy for the users to handle inline the key. So our examples are towards this direction:
```
connection = Connection(api_key=signal_ocean_api_key)
distances_api = DistancesAPI(connection)
```
Check also:
https://github.com/SignalOceanSdk/SignalSDK/blob/master/docs/examples/jupyter/DistancesAPI/QuickStartDistancesAPI.ipynb

could you adjust accordingly?

2020-12-10 08:30 UTC, prompanos-signal commented on docs/examples/jupyter/PortExpensesAPI/PortExpensesAPI.ipynb
> +    "port_id = 3153\n",
This is is not a universal identifier for the ports

so we cannot expose as it. What we have done in the other apis is to expose endpoints to get the available ports and do some filtering over it i.e:

https://github.com/SignalOceanSdk/SignalSDK/blob/c73bf6d2e1dabaf3419cfd8e67a5fc1153cb8dd9/signal_ocean/freight_pricing/freight_pricing_api.py#L77

if this is not possible through the port expenses, then the other option is to use the geo api:
https://github.com/SignalOceanSdk/SignalSDK/blob/c73bf6d2e1dabaf3419cfd8e67a5fc1153cb8dd9/signal_ocean/geo/geo_api.py#L67

This would require a small extension to create the filtering also in there.

2020-12-10 12:10 UTC, ktsitsikas-signal commented on docs/examples/jupyter/PortExpensesAPI/PortExpensesAPI.ipynb
> +    "port_id = 3153\n",
Added port filter in geo API and used it in jupyter examples. Also added Geo in APIs in test and prod APIMS port expenses products.

2020-12-17 15:41 UTC, prompanos-signal requested changes

2020-12-17 15:41 UTC, prompanos-signal commented on docs/examples/jupyter/PortExpensesAPI/PortExpensesAPI.ipynb
> +    "signal_ocean_api_key = '5d15f84a7741409fa64554c30df7c77a' #replace with your subscription key"
Please remove and refresh your key

2020-12-17 15:49 UTC, prompanos-signal approved these changes

2020-12-17 16:19 UTC, merged