https://thesignalgroup.atlassian.net/browse/PT-4053
SignalOceanSdk/SignalSDK pull request #25
Opened 2020-12-18 08:36 UTC by LamprosArgy

This example is the product of the following story:
https://thesignalgroup.atlassian.net/browse/PT-4053

2020-12-29 17:25 UTC, prompanos-signal requested changes
Please change also the following things:
- The pull request title, as the link targets an internal task while this is a public repo.
- Add a reference on `mkdocs.yml` (here : https://github.com/SignalOceanSdk/SignalSDK/blob/c8d3053c628ae3583db7b4650a10e58a5f1dae16/mkdocs.yml#L29) so as this is autogenerated as a documentation, like the rest of the examples we have (i.e: https://signaloceansdk.github.io/SignalSDK/examples/jupyter/VoyagesAPI/VoyagesAPI-UseCases/)

2020-12-29 17:25 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "def get_opening_event(id_of_prev_voy):\n",
I challenge we need all this complex operation. Why `VoyageStart` event is not enough for our purposes?

2020-12-29 17:25 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "def get_load_event(voyage_events):\n",
I suggest the following optimizations:
Create a mapping (i.e: dictionary from Api properties towards report properties)
Iterate on them to avoid writing the same code again

2020-12-29 17:25 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "def get_load_event(voyage_events):\n",
Also is there any chance to merge this and `get_discharge_event` into a single function that can take the event type as a parameter.?

2020-12-29 17:25 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "voyages_of_interest.to_excel('voyages_data_likeV2.xlsx')"
This seems to fail on me as `to_excel` cannot handle timezones. See:
https://stackoverflow.com/questions/16628819/convert-pandas-timezone-aware-datetimeindex-to-naive-timestamp-but-in-certain-t

2021-01-04 17:24 UTC, abelesiotis-signal requested changes

2021-01-04 17:24 UTC, abelesiotis-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "for col in voyages.columns.tolist():\n",
This cell should not be necessary. If the problem is filtering the dataframe with a time zone naive datetime, you can instantiate `date_from` as a timezone aware datetime with something like `date_from = datetime.now(timezone.utc) - timedelta(days=100) `

2021-01-04 17:24 UTC, abelesiotis-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "voy_df_for_iterations = voyages_of_interest.dropna(axis=0, subset=['load_event'])\n",
Not sure if  `voy_df_for_iterations ` is necessary. After creating the column with the event, I would suggest to populate the required entities (for load, discharge and open related information) with something like:

voyages_of_interest['load_port'] = voyages_of_interest['load_event'].apply(lambda e: e['port_name'] if e else None)

2021-01-04 17:24 UTC, abelesiotis-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "voyages_of_interest.loc[voyages_of_interest.discharge_event.notna(),'sts_discharge_ind'] = \\\n",
Since the logic to identify the indicator is written in a function, I would suggest to apply it to the entire series and handle `nan` values inside the function to make such blocks more readable.

2021-01-04 17:24 UTC, abelesiotis-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "voyages_of_interest.drop(unwanted_columns,axis=1,inplace=True)"
I would suggest to specify the wanted columns and filter using these instead of dropping the columns that are not necessary. We may introduce additional attributes in voyages in the future that may be irrelevant for the report and it would be better not to add these by default.

2021-01-11 06:02 UTC, LamprosArgy commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +   "cell_type": "markdown",
I am using the same structure of the cells like in VoyagesAPI-UseCases.ipynb, for the imports and the Connection.

2021-01-11 06:03 UTC, LamprosArgy commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "relaxed_date_from = date_from - timedelta(days=360)\n",
![image](https://user-images.githubusercontent.com/62944620/104150681-5396b780-53e3-11eb-9346-5f59b489d053.png)
I do not know the mechanics behind it, but as we have discussed with @abelesiotis-signal, there seems to be a big difference in the results as well.

2021-01-15 12:56 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "## Voyages API Voyages Like Use Case"
The title here is not needed

2021-01-15 12:56 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "relaxed_date_from = date_from - timedelta(days=360)\n",
The description is better. However, the performance is awful. can we go 3 months back in time?

2021-01-15 12:56 UTC, prompanos-signal commented on docs/examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb
> +    "                  'opening_event',\n",
I think we should expose in the final document opening_event, load_event and discharge_event. This seems strange:
![image](https://user-images.githubusercontent.com/71878165/104729627-60980b80-5741-11eb-9f98-ec5e0f63ffa8.png)

2021-01-27 22:10 UTC, prompanos-signal approved these changes

2021-01-28 07:17 UTC, abelesiotis-signal approved these changes

2021-01-29 10:13 UTC, merged