Feature/devops 249 implement tests for sdk
SignalOceanSdk/SignalSDK pull request #46
Opened 2021-03-11 11:17 UTC by thomasklepacki

I have temporarily created a separate build configuration for running notebooks:
http://teamcity.signalocean.com/viewLog.html?buildId=293263&buildTypeId=FrontEnd_PythonSdk_NotebookRunner
When PR will be merged to develop I will add needed steps to Release Test Package Build Configuration and delete temporary build.

2021-03-12 13:15 UTC, pogrodowczyk requested changes

2021-03-12 13:15 UTC, pogrodowczyk commented on nbrunner.sh
> +sed -i "s/signal_ocean_api_key = 'Not Valid'/signal_ocean_api_key = '$apikey'/" docs/examples/jupyter/*/"$filename";
I'm afraid this is not sustainable. We would have to cater to every possible variable name and code structure that someone could put in a notebook, and modify this script when that happens.

Instead, you could update the existing notebooks to initialize the API key with an empty string. If the string is not replaced with a user's API key, it will cause the SDK to fall back to using the `SIGNAL_OCEAN_API_KEY` environment variable. Since in this script you're already requiring `SIGNAL_OCEAN_API_KEY` to be present, you could then simply remove these lines and the notebooks would work "out of the box".

2021-03-12 13:15 UTC, pogrodowczyk commented on nbrunner.sh
> +done
Please add a newline at the end of this file.

2021-03-17 12:09 UTC, thomasklepacki commented on nbrunner.sh
> +apikey=$(printf '%s\n' "${!env_name}");
Indeed. Fixed.

2021-03-17 12:09 UTC, thomasklepacki commented on nbrunner.sh
> +~/.local/bin/jupyter nbconvert --execute --clear-output docs/examples/jupyter/*/"$filename";
Of course. Fixed.

2021-03-17 12:10 UTC, thomasklepacki commented on nbrunner.sh
> +sed -i "s/signal_ocean_api_key = 'Not Valid'/signal_ocean_api_key = '$apikey'/" docs/examples/jupyter/*/"$filename";
Good point! Works without api key replacement mechanism.

2021-03-17 12:10 UTC, thomasklepacki commented on nbrunner.sh
> +done
Done.

2021-03-17 12:37 UTC, pogrodowczyk approved these changes

2021-03-22 08:44 UTC, merged