multiple vesselclasses, optional subclass
SignalOceanSdk/SignalSDK pull request #5
Opened 2020-10-08 08:22 UTC by athanbonis-signal

- Multiple Vessel Classes added
- Subclass as optional parameter

2020-10-09 12:14 UTC, gsafalidis-signal submitted a review, later dismissed

2020-10-09 13:08 UTC, pogrodowczyk requested changes

2020-10-09 13:08 UTC, pogrodowczyk commented on signal_ocean/freight_pricing/freight_pricing_api.py
> +            *vessel_class: VesselClass) -> Tuple[FreightPricing, ...]:
`*vessel_class` might become problematic if we decide to add more arguments to this method in the future. I think `vessel_classes: Optional[Tuple[VesselClass, ...]] = None` would be better.

2020-10-09 13:08 UTC, pogrodowczyk commented on signal_ocean/freight_pricing/freight_pricing_api.py
> +        if len(vessel_class) != 0:
This block could be simplified to a list comprehension.

2020-10-09 13:23 UTC, athanbonis-signal commented on signal_ocean/freight_pricing/freight_pricing_api.py
> +            *vessel_class: VesselClass) -> Tuple[FreightPricing, ...]:
Yes, I think you are right. Let me change it.

2020-10-12 10:44 UTC, prompanos-signal submitted a review, later dismissed

2020-10-12 11:07 UTC, pogrodowczyk commented on signal_ocean/freight_pricing/freight_pricing_api.py
> +                if len(vessel_classes) != 0
I think you meant something else here because this will check the length of `vessel_classes` for each `vc` . You can remove this condition completely.

2020-10-12 11:07 UTC, pogrodowczyk submitted a review, later dismissed

2020-10-12 11:10 UTC, athanbonis-signal commented on signal_ocean/freight_pricing/freight_pricing_api.py
> +                if len(vessel_classes) != 0
Maybe this check should go to the outside if because I wanted to do something like NullOrEmpty check.

2020-10-13 08:13 UTC, pogrodowczyk approved these changes

2020-10-13 09:05 UTC, merged