Feature/voyages api advanced search
SignalOceanSdk/SignalSDK pull request #72
Opened 2021-06-18 16:04 UTC by miltonlog

2021-07-02 09:06 UTC, abelesiotis-signal requested changes

2021-07-02 09:06 UTC, abelesiotis-signal commented on signal_ocean/voyages/voyages_api.py
> +        args = endpoint_params.keys()
You can use `urllib.parse.urlencode` to encode the dictionary to the url string.

2021-07-02 09:06 UTC, abelesiotis-signal commented on signal_ocean/voyages/voyages_api.py
> +    def _get_advanced_endpoint(**endpoint_params) -> str:
Unit tests for this function should be added, please check `tests.voyages.test_voyages` for reference.

2021-07-02 09:06 UTC, abelesiotis-signal commented on signal_ocean/voyages/voyages_api.py
> +    def get_voyages_by_advanced_search(self,
Unit tests for this function should be added, please check `tests.voyages.test_voyages` for reference.

2021-07-02 11:32 UTC, abelesiotis-signal commented on signal_ocean/voyages/voyages_api.py
> +    def get_voyages_by_advanced_search(self,
It will also be good to have a couple of examples on calling this function with different combination of arguments in `VoyagesApi.ipynb` in the notebook examples folder for voyages-api. There are other examples of the calls a user can make there.

2021-07-06 12:08 UTC, abelesiotis-signal commented on tests/voyages/test_voyages.py
> +    id= 'I8BFD7DVED758D000', imo = 9174397,
Please use anonymized IMO, vessel name, commercial operator similar to the previous examples here.

2021-07-06 12:11 UTC, abelesiotis-signal commented on tests/voyages/test_voyages.py
> +    expected = _mock_get_advanced_search.pop('expected')
It's better not to mutate the object here. Break it down to two inputs, or used a dict or for separate entries for input and expected output and get the values required here.

2021-07-06 12:11 UTC, abelesiotis-signal commented on tests/voyages/test_voyages.py
> +    for i, key in enumerate(_mock_get_advanced_search):
It would be better to construct to use a preconstructed input and refrain from using conditional logic within the test function.

2021-07-08 13:12 UTC, prompanos-signal approved these changes

2021-07-08 13:30 UTC, prompanos-signal approved these changes

2021-07-08 13:30 UTC, prompanos-signal approved these changes

2021-07-08 13:31 UTC, merged