Oilx data integration
SignalOceanSdk/SignalSDK pull request #79
Opened 2021-09-07 12:01 UTC by LamprosArgy

2021-09-08 09:47 UTC, abelesiotis-signal requested changes

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from datetime import date
Tests should be added for the calls in the API. Please have a look at `test_voyages.py` for examples.

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from typing import Optional, Tuple, List
It would also be helpful to add a notebook with the calls in the examples folder to present usage (similar to `VoyagesAPI.ipynb`).

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from signal_ocean.util.request_helpers import get_single, get_multiple
There are some unused references here.

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +    def _get_endpoint(vessel_class_id: Optional[int] = None,
Functionality for incremental seems mostly implemented, but not exposed to the user. Perhaps it would be good to add a call exposing it.

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_models.py
> +        gravity_band:
Please add a simple description for the fields where it is missing.

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/util/parsing_helpers.py
>              except (TypeError, ValueError):
The change here modifies the behavior of the function. The implemented logic when having a type hint such as Union[int, float] will iterate over the candidate types and try to instantiate the appropriate class. It will only fail only if none of the specified types match. The modified code will raise an error if parsing fails for the first candidate class. The change breaks a unit test for the function.

2021-09-08 09:47 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +            return tuple(results), next_request_token
The `return` statement (and the assignment of the `next_request_token`) should be placed outside of the while loop. The current implementation of the method will only return the first page of the results.

2021-11-01 09:18 UTC, LamprosArgy commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from datetime import date
I have created tests for cargo tracking api. Thanks!

2021-11-01 09:20 UTC, LamprosArgy commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from typing import Optional, Tuple, List
I have created a notebook regarding oilx data, but this branch should be merged with develop first because at the moment I do local installation of signal_ocean library for the notebook to run.

2021-11-01 09:20 UTC, LamprosArgy commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from signal_ocean.util.request_helpers import get_single, get_multiple
I have cleaned the code. Thank you!

2021-11-01 09:20 UTC, LamprosArgy commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +    def _get_endpoint(vessel_class_id: Optional[int] = None,
I have implemented the incremental call as well.

2021-11-01 09:21 UTC, LamprosArgy commented on signal_ocean/oilx_cargo_tracking/oilx_models.py
> +        gravity_band:
Done. Thank you!

2021-11-01 09:21 UTC, LamprosArgy commented on signal_ocean/util/parsing_helpers.py
>              except (TypeError, ValueError):
I reverted the logic. Thank you!

2021-11-02 09:33 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_models.py
> +    load_geoasset_id: Optional[int] = None
The property `load_geoasset_id` is not automatically mapped to `LoadGeoAssetID` as the mapper relies on capitalization to convert between snake case and camel case. As a result, all data returned have None value in the  CargoFlow model. One option would be to extend the mapping function, but the easiest here is to change the property name to `load_geo_asset_id`. Same applies for `discharge_geoasset_id`.

2021-11-02 10:49 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +    ) -> CargoFlows:
Type hint for return value should be `Tuple[CargoFlows, Optional[str]]` here.

2021-11-02 10:51 UTC, abelesiotis-signal commented on signal_ocean/oilx_cargo_tracking/oilx_cargo_tracking_api.py
> +from signal_ocean.util.request_helpers import get_single, get_multiple
Imports `from datetime import date` and `urlencode` are also unused.

2021-11-04 11:07 UTC, abelesiotis-signal commented on tests/oilx_cargoes/test_oilx_cargoes.py
> +    assert oilx_cargoes, _ == _mock_oilx_cargoes
The assertion here should be `assert oilx_cargoes == _mock_oilx_cargoes`. Also, the correct assertion would fail now as `LoadGeoAssetID` and `DischargeGeoAssetID` have the actual values, but `load_geo_asset_id `and `discharge_geo_asset_id`  are `None`. Please, fill in `load_geo_asset_id `and `discharge_geo_asset_id` with the appropriate values.

2021-11-04 11:07 UTC, abelesiotis-signal commented on tests/oilx_cargoes/test_oilx_cargoes.py
> +    assert oilx_cargoes, _ == _mock_oilx_cargoes
Similarly to above, the assertion here should be `assert oilx_cargoes == _mock_oilx_cargoes`.

2021-11-04 11:27 UTC, abelesiotis-signal commented on tests/oilx_cargoes/test_oilx_cargoes.py
> +    api_gravity=None,
Here should be `api_gravity=37.30`.

2021-11-04 11:27 UTC, abelesiotis-signal commented on tests/oilx_cargoes/test_oilx_cargoes.py
> +    api_gravity=None,
Also, here should be `api_gravity=37.30`.

2021-11-04 11:56 UTC, abelesiotis-signal commented on tests/oilx_cargoes/test_oilx_cargoes.py
> +    api_gravity=None,
The regex in `_to_snake_case` in `parsing_helpers.py` cannot handle the transformation of `APIGravity`. It needs to be modified to something like the following to detect the change from capital to lower case letter to work. 

```
def _to_snake_case(s: str) -> str:
    """Transforms a string from CapWords to snake_case.

    Args:
        s: The string to transform

    Returns:
        The transformed string
    """
    s = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', s)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s).lower()
```
If you fix this please also add a test case in `test_to_snake_case` function in `test_parsing_helpers.py` for `APIGravity`.

2021-11-04 17:13 UTC, abelesiotis-signal approved these changes

2021-11-04 17:55 UTC, merged